const { describe, it } = require("node:test");
const assert = require("node:assert/strict");
const {
  buildCatalogSampleLine,
  clampTtsSpeed,
  isValidFishReferenceId,
  resolveCatalogTtsSpeed,
  unifiedPreviewCacheKey,
} = require("./voice-catalog");

describe("voice-catalog", () => {
  it("uses intro sample line per voice", () => {
    assert.match(buildCatalogSampleLine("Maes", "fr"), /Maes/i);
    assert.match(buildCatalogSampleLine("Maes", "fr"), /LuxeFlexIA/i);
    assert.match(buildCatalogSampleLine("Maes", "en"), /generated by LuxeFlexIA/i);
    assert.match(buildCatalogSampleLine("Maes", "es"), /generado por LuxeFlexIA/i);
  });

  it("validates fish reference ids", () => {
    assert.equal(
      isValidFishReferenceId("6be490a175744894826dd464cf3a5004"),
      true,
    );
    assert.equal(isValidFishReferenceId("invalid"), false);
  });

  it("builds stable cache keys", () => {
    assert.equal(
      unifiedPreviewCacheKey("6BE490A175744894826DD464CF3A5004", "fr"),
      "voice-catalog/unified/v7/fr/6be490a175744894826dd464cf3a5004.mp3",
    );
  });

  it("resolves Fish TTS speed from catalog rate × pitch (grave = plus lent)", () => {
    assert.ok(
      Math.abs(
        resolveCatalogTtsSpeed("3cfa191ad09b4cfea8e4eebc4c31c923") - 0.816,
      ) < 0.001,
    );
    assert.ok(
      Math.abs(
        resolveCatalogTtsSpeed("22b7c6809d5d405aa6a5ae2402272b53") - 0.655,
      ) < 0.001,
    );
    assert.ok(
      Math.abs(
        resolveCatalogTtsSpeed("0ff4b00e39e2429981b93bd7c6256d98") - 0.684,
      ) < 0.001,
    );
    assert.equal(resolveCatalogTtsSpeed("not-a-catalog-id"), null);
  });

  it("clamps tts speed to safe bounds", () => {
    assert.equal(clampTtsSpeed(2), 1.35);
    assert.equal(clampTtsSpeed(0.2), 0.65);
  });
});
