/** Scripts voix landing + catalogue — FR / EN / ES. */
import { normalizeLocale, type AppLocale } from "./locales";

export type VoiceScriptLocale = "fr" | "en" | "es";

const LANDING_NATURAL_MALE: Record<VoiceScriptLocale, string> = {
  fr: "Bonjour, voici une voix masculine naturelle — générée par LuxeFlexIA.",
  en: "Hello, this is a natural male voice — generated by LuxeFlexIA.",
  es: "Hola, esta es una voz masculina natural — generada por LuxeFlexIA.",
};

const LANDING_NATURAL_FEMALE: Record<VoiceScriptLocale, string> = {
  fr: "Bonjour, voici une voix féminine naturelle — générée par LuxeFlexIA.",
  en: "Hello, this is a natural female voice — generated by LuxeFlexIA.",
  es: "Hola, esta es una voz femenina natural — generada por LuxeFlexIA.",
};

export function normalizeVoiceLocale(value: string | null | undefined): VoiceScriptLocale {
  const locale = normalizeLocale(value);
  if (locale === "en" || locale === "es") return locale;
  return "fr";
}

/** Intro catalogue — « Salut, c'est Maes — généré par LuxeFlexIA » (par voix). */
export function buildCatalogSampleLine(
  name: string,
  localeLike?: string | null,
): string {
  return buildLandingVoiceScript({ name, demoKind: "artist" }, localeLike);
}

/** @deprecated utiliser buildCatalogSampleLine(name) */
export function getCatalogSampleLine(nameOrLocale?: string | null, localeLike?: string | null): string {
  const maybeLocale = normalizeLocale(nameOrLocale);
  if (maybeLocale === "en" || maybeLocale === "es" || maybeLocale === "fr") {
    return buildCatalogSampleLine("LuxeFlexIA", maybeLocale);
  }
  return buildCatalogSampleLine(String(nameOrLocale || "LuxeFlexIA"), localeLike);
}

export function buildLandingVoiceScript(
  entry: { name?: string; demoKind?: string },
  localeLike?: string | null,
): string {
  const locale = normalizeVoiceLocale(localeLike);
  if (entry.demoKind === "natural-male") return LANDING_NATURAL_MALE[locale];
  if (entry.demoKind === "natural-female") return LANDING_NATURAL_FEMALE[locale];
  const name = String(entry.name || "").trim() || "LuxeFlexIA";
  if (locale === "en") return `Hi, I'm ${name} — generated by LuxeFlexIA.`;
  if (locale === "es") return `Hola, me presento, soy ${name} — generado por LuxeFlexIA.`;
  return `Salut, je me présente, c'est ${name} — j'ai été généré par LuxeFlexIA.`;
}

export function speechSynthesisLang(localeLike?: string | null): string {
  const locale = normalizeVoiceLocale(localeLike);
  if (locale === "en") return "en-US";
  if (locale === "es") return "es-ES";
  return "fr-FR";
}
